const ELEMENT = [
  { element: "AC" },
  { element: "+/-" },
  { element: "%" },
  { element: "÷", operator: true },
  { element: 7 },
  { element: 8 },
  { element: 9 },
  { element: "x", operator: true },
  { element: 4 },
  { element: 5 },
  { element: 6 },
  { element: "-", operator: true },
  { element: 1 },
  { element: 2 },
  { element: 3 },
  { element: "+", operator: true },
  { element: "0" },
  { element: "." },
  { element: "=" },
];
export default ELEMENT;
